### ISSUE TITLE
[Feature Request] Allow using local RSS file

### ISSUE THREAD

**Issue by TheGroundZero** [CodingBull-dev/newest-rss-post-action#1]
I´d like to use this action as part of publishing my static website.
This website is first build in Hugo, then pushed to GitHub pages.
So there's a delay between building the site and the update being available online.
However, the RSS file is creating during the build stage.

As such, it would be nice to do e.g. 

```yaml
name: Deploy page

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy page
        uses: my-repo/page-deployer

  publish:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Fetch RSS Data
        id: rss
        uses: CodingBull-dev/newest-rss-post-action@main
        with:
          rss: ./public/blog/rss.xml  # <---- use local file instead of remote
```

If this is already supported, could the documentation be updated to reflect this and to indicate what the path format should be?
